const constants = {
    ADMIN : 'admin',
    USER : 'user',
    OPEN_POLES : 'Open Poles',
    ADD_POLE : "Add Pole",
    CLOSE_POLES : "Close Poles",
    OPEN_LIST : "Open List",
    EDIT : "Edit",
    DELETE : "Delete",
    CLOSE : "Close",
    WILL_EXPIRE_ON : "Will expire on ",
    EXPIRED_ON : "Expired on ",
    LIST_IS_EMPTY : "Oops! List is empty",
    ADD : 'Add',
    Edit : 'Edit',
    VALID : "Valid",
    EDIT_POLE : "Edit Pole",
    CLOSE_DATE_ERROR : "Closing date should be greater than current date",
    INVALID_DATE : "Invalid Date",
    POLE_NAME_ALREADY_EXIST : "Pole name already exist",
    INCORRECT_PASSWORD : "Incorrect Password",
    LOGIN : "Login",
    REGISTER : "Register",
    USERNAME : "User name",
    PASSWORD : "Password",
    REDIRECT_TO_REGISTER_MESSAGE : " Don't have an account? Click to register",
    USERNAME_INVALID_ERROR : "User name is not valid",
    SOMETHING_WENT_WRONG : "Something went wrong",
    REDIRECT_TO_LOGIN_MESSAGE : "Already have an account? Go to login",
    ROLE : 'Role',
    CONFIRM_PASSWORD : "Confirm password",
    FIRST_NAME : "First name",
    LAST_NAME : "Last name",
    USER_CREATED_MESSAGE : "User created successfully",
    USER_NAME_EXIST : "User name already exist",
    PASSWORD_MISMATCH_ERROR : "Confirm Password & Password didn't match",
    POLE_RESULT : "Pole Result",
    POLE_DETAILS : "Pole Details",
    CANCEL : "Cancel",
    SAVE : "Save",
    POLE_NAME : "Pole Name",
    CLOSING_DATE : "Closing Date",
    OPTION : "Option",
    ADD_OPTION : "+ Add option",
    ADD_QUESTION : "+ Add question",
    RESULT : "Result",
    VISITED_BY:"Visited by",
    USERS : "users",
    CLOSE_LIST : "Clost list",
    POLE_SYSTEM : "Pole system",
    LOG_OUT : "Log out"

}


export default constants