const ADD_USER = "ADD_USER"
const LOG_IN_USER = "LOG_IN_USER"
const LOG_OUT = "LOG_OUT"
const ADD_POLE = "ADD_POLE"
const DELETE_POLE = "DELETE_POLE"
const MODIFY_POLE = "MODIFY_POLE"


export {
    ADD_USER,
    LOG_IN_USER,
    LOG_OUT,
    ADD_POLE,
    DELETE_POLE,
    MODIFY_POLE,
}